import { ApolloWrapper } from "@/graphql/apollo_wrapper";

//export const metadata = {
//  title: "Create Next App",
//  description: "Generated by create next app",
//};


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <ApolloWrapper>
            {children}
        </ApolloWrapper>
      </body>
    </html>
  );
}
